APP_NAME=Laravel
APP_ENV=local
APP_KEY=base64:U1SdgNrjFLNdp67ELTfnbopOq6LmGdS/jF3u/Yw3Z40=
APP_DEBUG=true
APP_URL=https://file.klientscape.com/

LOG_CHANNEL=stack

DB_CONNECTION=mysql
DB_HOST=127.0.0.1
DB_PORT=3306
DB_DATABASE=klientscape_filemgmt
DB_USERNAME=klientscape_filemgmt
DB_PASSWORD=klientscape_filemgmt

BROADCAST_DRIVER=log
CACHE_DRIVER=file
QUEUE_CONNECTION=sync
SESSION_DRIVER=file
SESSION_LIFETIME=120

REDIS_HOST=127.0.0.1
REDIS_PASSWORD=null
REDIS_PORT=6379

MAIL_DRIVER=smtp
MAIL_HOST=mail.klientscape.com
MAIL_PORT=465
MAIL_USERNAME=no-reply@klientscape.com
MAIL_PASSWORD=no-reply@123
MAIL_ENCRYPTION=ssl

AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=
AWS_DEFAULT_REGION=us-east-1
AWS_BUCKET=

PUSHER_APP_ID=1239028
PUSHER_APP_KEY=024357e91dcc13a50135
PUSHER_APP_SECRET=9ee87ce478aa059a9db9
PUSHER_APP_CLUSTER=ap2

MIX_PUSHER_APP_KEY="${PUSHER_APP_KEY}"
MIX_PUSHER_APP_CLUSTER="${PUSHER_APP_CLUSTER}"
